version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tizora_postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: tizora
      PGTZ: Asia/Kolkata
    ports:
      - '5433:5432'
    volumes:
      - tizora_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  tizora_postgres_data:
